spring.application.name=lesson4

spring.application.pathinput = C:\\java\\
spring.application.pathoutput = C:\\send\\send.txt

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=baeldung

spring.shell.interactive.enabled=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql

spring.sql.init.mode=always

